// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

package server

import (
	"context"

	"github.com/zxmfke/lgtm/example/go-zero-lgtm/user/rpc/internal/logic"
	"github.com/zxmfke/lgtm/example/go-zero-lgtm/user/rpc/internal/svc"
	"github.com/zxmfke/lgtm/example/go-zero-lgtm/user/rpc/userclient"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) GetUser(ctx context.Context, in *userclient.IdRequest) (*userclient.UserResponse, error) {
	l := logic.NewGetUserLogic(ctx, s.svcCtx)
	return l.GetUser(in)
}
